# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Excessive-dependence-solution' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Excessive-dependence-solution
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Analytics'
	pod 'Firebase/Database'

  target 'Excessive-dependence-solutionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Excessive-dependence-solutionUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
